name: GitHub Classroom Workflow

on: push, workflow_dispatch

permissions:
  checks: write
  issues: write
  actions: read
  contents: read

jobs:
  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    uses: ghwalin/autograde_python/.github/workflows/grading.yml@main
    with:
      MOODLE: true  # CHANGE true=export grade to moodle
    secrets: inherit